#!/bin/sh
#
# /etc/rc.d/template: start/stop template
#

# Load configuration and functions
. /etc/rc.conf
. /etc/conf.d/functions

NAME="template daemon"
PROG=/usr/bin/foo
OPTS="--background"
PROCPID=$(pidof $PROG)
PROGNAME=$(basename `echo $PROG`)
PIDFILE=/var/run/$PROGNAME.pid

case $1 in
	start)
		msg "Starting $NAME..."
		if [ "$PROCPID" ]; then
			exit
		fi
		$PROG $OPTS
		check_retval
		;;
	stop)
		msg "Stopping $NAME..."
		if [ "$PROCPID" ]; then
			for pid in $PROCPID; do
				kill "$pid"
			done
		fi
		rm -f $PIDFILE
		check_retval
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		if [ "$PROCPID" ]; then
			echo "$NAME is running with pid: $PROCPID"
		else
			echo "$NAME is not running."
		fi
		;;
	*)
		echo "usage: $0 [start|stop|restart|status]"
		;;
esac

exit 0

# End of file
