#!/bin/sh
#
# /etc/rc.d/template: start/stop template
#

PROG=/usr/bin/foo
PROGNAME=$(basename `echo $PROG`)
PIDFILE=/var/run/PROGNAME.pid
OPTS="--background"
PROCPID=$(pidof $PROGNAME)

case $1 in
	start)
		if [ -f $PIDFILE ]; then
			echo "$PROGNAME is already running"
			exit 1
		fi
		echo "Starting $PROGNAME daemon..."
		$PROG $OPTS
        ;;
	stop)
		if [ ! -f $PIDFILE ]; then
			echo "$PROGNAME is not running"
			exit 1
		fi
		echo "Stopping $PROGNAME daemon..."
		for pid in $PROCPID; do
			kill $pid
		done
        ;;
	restart)
        $0 stop && $0 start
        ;;
	status)
		if [ "$PROCPID" ]; then
			echo "$PROGNAME is running with pid: $PROCPID"
		else
			echo "$PROGNAME is not running"
		fi
		;;
*)
        echo "usage: $0 [start|stop|restart|status]"
        ;;
esac

