#!/bin/bash

# Load configuration
. /etc/rc.conf

red='\e[0;31m'      #Red
green='\e[0;32m'    #Green
yellow='\e[0;33m'   #Yellow
blue='\e[0;34m'     #Blue
purple='\e[0;35m'   #Purple
cyan='\e[0;36m'     #Cyan
gray='\e[0;37m'     #Gray
reset='\e[0m' 	  #Reset color

dprint() {
	echo -e "[ ${red}*${reset} ] $@"
}

eprint() {
	echo -e "[ ${green}*${reset} ] $@"
}

rc_status() {
	
	for daemon in ${DAEMONS[@]}; do
		if [ -f /etc/rc.d/$daemon ]; then
			if [ -x /etc/rc.d/$daemon ]; then
				eprint "$daemon"
			else
				dprint "$daemon"
			fi
		fi
	done

}

rc_enable() {
	
	if [ -f /etc/rc.d/$1 ]; then
		if [ ! -x /etc/rc.d/$1 ]; then
			chmod +x /etc/rc.d/$1 && echo "$1 daemon enabled"
		else
			echo "daemon $1 already enabled"
		fi
	else
		echo "daemon $1 not exist!"
	fi
	
}

rc_disable() {
	
	if [ -f /etc/rc.d/$1 ]; then
		if [ -x /etc/rc.d/$1 ]; then
			chmod -x /etc/rc.d/$1 && echo "$1 daemon disabled"
		else
			echo "daemon $1 already disabled"
		fi
	else
		echo "daemon $1 not exist!"
	fi
	
}

rc_options() {
	
	/etc/rc.d/$2 $1
	
}

help() {
	
	cat << EOF
rc-init daemon control script

usage:
  rc [ <option> <arguments> ]
		
options:
  enable  <daemons>  enable daemon
  disable <daemons>  disable daemon
  start   <daemons>  start the daemons
  restart <daemons>  restart the daemons
  stop    <daemons>  stop the daemons
  status  <daemons>  show the daemons status
EOF

}

if [ -z "$1" ]; then
	rc_status
	exit 0
else
	while [ $1 ]; do
		case $1 in
			enable)
				while [ $2 ]; do
					rc_enable $2
					shift
				done
				;;
			disable)
				while [ $2 ]; do
					rc_disable $2
					shift
				done
				;;
			start)
				while [ $2 ]; do
					rc_options start $2
					shift
				done
				;;
			restart)
				while [ $2 ]; do
					rc_options restart $2
					shift
				done
				;;
			stop)
				while [ $2 ]; do
					rc_options stop $2
					shift
				done
				;;
			status)
				while [ $2 ]; do
					rc_options status $2
					shift
				done
				;;
			*|help)
				help
				exit 0
				;;
		esac
		shift
	done
fi

exit 0
