#!/bin/sh
#
# /etc/conf.d/functions function load by initscripts and daemons
#

# color codes and some predefined texts
BOLD="\033[1m"
NORM="\033[0m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"

OK="${GREEN}OK${NORM}"
FAILED="${RED}FAILED${NORM}"
DONE="${GREEN}DONE${NORM}"

# check an exit value and print a colored status
check_retval() {
	if [ $? -ne 0 ]
	then
		stat_failed
	else
		stat_ok
	fi
}

# print a colored done status
stat_done() {
	echo -e " $DONE"
}

# print a colored ok status
stat_ok() {
	echo -e " $OK"
}

# print a colored failed status
stat_failed() {
	echo -e " $FAILED"
}

# print a colored '*' for message
msg() {
	echo -ne " ${BLUE}*${NORM} $1"
}

# End of file
